#!/bin/bash
username=$1
updown=$2
userip=$3
userpid=$4
userdir=$5

ruledir="$userdir/$username"
rulefileup="$ruledir/uprules"
rulefiledown="$ruledir/downrules"
trap '' 1 2 3 4 5 6 7 8 10 12 13 14 15 20    # user must not be able to escape this script
if [ ! -f $rulefileup ]; then
	exit
elif [ ! -f $rulefileup ]; then
	exit	# exit silently if no rules exist
fi


if [ $# != 5 ]
then
	echo "Usage: ${0} username {up|down} userip userpid /user/directory"
	exit
fi

if [ "${updown}" = "up" ]
then
	rulefile=$rulefileup
else
	rulefile=$rulefiledown
fi

sed "s/\$userip/${userip}/g;s/\$username/${username}/g;s/\$userpid/${userpid}/g" $rulefile | sudo /sbin/iptables-restore -n
exit
